import { ReactNode } from 'react';
import { SessionProvider } from 'next-auth/react';

import { inter } from '@/lib/fonts';

import { auth } from '@/auth';

import { Header } from '@/app/components/Header';
import { AppSidebar } from '@/app/components/AppSidebar';
import { ThemeProvider } from '@/app/components/ThemeProvider';

import { SidebarProvider } from '@/components/ui/sidebar';

import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <SessionProvider session={session}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <SidebarProvider defaultOpen={false}>
              <AppSidebar />
              <div className="flex flex-col w-full">
                <Header />
                <main className="grow flex flex-col">{children}</main>
              </div>
            </SidebarProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
