import { ReactNode } from 'react';
import { SessionProvider } from 'next-auth/react';
import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

import { inter } from '@/lib/fonts';

import { routing } from '@/i18n/routing';
import { auth } from '@/auth';

import { ThemeProvider } from '@/app/[locale]/components/ThemeProvider';
import { AppSidebar } from '@/app/[locale]/components/AppSidebar';
import { Header } from '@/app/[locale]/components/Header';

import { SidebarProvider } from '@/components/ui/sidebar';

import '../globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();
  const session = await auth();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <SessionProvider session={session}>
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <SidebarProvider defaultOpen={false}>
                <AppSidebar />
                <div className="flex flex-col w-full">
                  <Header />
                  <main className="grow flex flex-col">{children}</main>
                </div>
              </SidebarProvider>
            </ThemeProvider>
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
